"""initial schema

Revision ID: dc7395c96ecf
Revises: 
Create Date: 2026-09-14 05:37:28.179266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc7395c96ecf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS citext')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_table('donors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('marketing_consent', sa.Boolean(), nullable=False),
    sa.Column('consent_recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_source', sa.String(length=120), nullable=True),
    sa.Column('manage_token_hash', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donors_email'), 'donors', ['email'], unique=True)
    op.create_table('posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body_md', sa.Text(), nullable=False),
    sa.Column('excerpt', sa.String(length=500), nullable=False),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_slug'), 'posts', ['slug'], unique=True)
    op.create_table('webhook_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('received', 'processed', 'failed', 'ignored', name='webhook_event_status'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_events_provider_event_id'), 'webhook_events', ['provider_event_id'], unique=True)
    op.create_table('data_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('donor_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('access', 'erasure', 'rectification', 'objection', name='data_request_type'), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fulfilled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_requests_donor_id'), 'data_requests', ['donor_id'], unique=False)
    op.create_table('email_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('donor_id', sa.UUID(), nullable=True),
    sa.Column('template', sa.String(length=120), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('sent', 'failed', name='email_status'), nullable=False),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('donor_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('stripe', 'paypal', 'mpesa_ratiba', 'test', name='subscription_provider'), nullable=False),
    sa.Column('provider_subscription_id', sa.String(length=255), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('interval', sa.Enum('monthly', name='subscription_interval'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'past_due', 'cancelled', 'failed', name='subscription_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_charge_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=500), nullable=True),
    sa.Column('cover_fees', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_subscription_id', name='uq_subscriptions_provider_subid')
    )
    op.create_index(op.f('ix_subscriptions_donor_id'), 'subscriptions', ['donor_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_next_charge_at'), 'subscriptions', ['next_charge_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_table('donations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('donor_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.Enum('stripe', 'paypal', 'mpesa_ratiba', 'test', name='subscription_provider'), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=255), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('fee_minor', sa.Integer(), nullable=True),
    sa.Column('net_minor', sa.Integer(), nullable=True),
    sa.Column('settled_kes_minor', sa.Integer(), nullable=True),
    sa.Column('fx_rate', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('status', sa.Enum('pending', 'succeeded', 'failed', 'refunded', name='donation_status'), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('btc_amount_sats', sa.Integer(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donations_donor_id'), 'donations', ['donor_id'], unique=False)
    op.create_index(op.f('ix_donations_provider_payment_id'), 'donations', ['provider_payment_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_donations_provider_payment_id'), table_name='donations')
    op.drop_index(op.f('ix_donations_donor_id'), table_name='donations')
    op.drop_table('donations')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_next_charge_at'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_donor_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_table('email_log')
    op.drop_index(op.f('ix_data_requests_donor_id'), table_name='data_requests')
    op.drop_table('data_requests')
    op.drop_index(op.f('ix_webhook_events_provider_event_id'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_posts_slug'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_donors_email'), table_name='donors')
    op.drop_table('donors')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
    op.execute('DROP EXTENSION IF EXISTS citext')
